config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions do
    get :make_recurring, on: :member
  end

  resources :plans

  post 'paypal/ipn_listener' => 'paypal#ipn_listener'

  root 'plans#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :paypal_description, length: { maximum: 120 }

  def paypal_description=(value)
    write_attribute(:paypal_description, I18n.transliterate(value))
  end

  def to_s
    name
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessor :paypal_payment_token

  belongs_to :plan

  delegate :price, :paypal_description, to: :plan

  def cancel!
    update(canceled: true)
  end

  def paid?
    return false if paid_until.blank?
    paid_until >= Time.current
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paypal_controller.rb
class PaypalController < ApplicationController
  protect_from_forgery except: [:ipn_listener]

  def ipn_listener
    Rails.logger.info "params received:"
    Rails.logger.info params
    if params[:txn_type].present?
      PaypalSubscription::NotificationHandler.resolve!(
        subscription: subscription,
        notification: notification
      )
    end

    render nothing: true
  end

  private

  def subscription
    @subscription ||=
      Subscription.find_by!(
        id: notification.reference,
        paypal_payer_id: notification.payer_id
      )
  end

  def notification
    @notification ||= PayPal::Recurring::Notification.new(params)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.all
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    @plan.update(params.require(:plan).permit(:name, :description, :paypal_description, :price))
    redirect_to [:edit, @plan]
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @subscriptions = Subscription.all
  end

  def show
  end

  def create
    @subscription = Subscription.create(subscription_params)
    redirect_to checkout_url
  end

  def make_recurring
    if PaypalSubscription::RecurrenceCreator.create!(
        subscription: subscription,
        paypal_options: paypal_options.merge({
          payer_id: params[:PayerID],
          token: params[:token]
        })
      )
      redirect_to subscription_path(subscription),
        notice: I18n.t('flashes.subscription.successfully_created')
    end
  end

  def destroy
    PaypalSubscription::ResourceFacade.cancel(paypal_options)

    redirect_to subscription_path(subscription),
      notice: I18n.t('flashes.subscription.cancellation_asked')
  end

  private

  def checkout_url
    PaypalSubscription::ResourceFacade.checkout_url(
      paypal_options.merge({
        return_url: make_recurring_subscription_url(subscription),
        cancel_url: subscription_url(subscription, aborting_operation: true)
      })
    )
  end

  def paypal_options
    @paypal_options ||=
      PaypalSubscription::DefaultOptions.for(subscription)
  end

  def subscription
    @subscription ||= Subscription.find(params[:id])
  end
  helper_method :subscription

  def subscription_params
    params.permit(:plan_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaypalSubscriptions</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css">
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/plans/edit.html.erb
<%= form_for @plan do |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.text_field :paypal_description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.number_field :price, step: 0.01, class: 'form-control' %>
    </div>

  <%= f.submit 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Plans', plans_path %>
<%end%>

app/views/plans/index.html.erb
<h1>Plans</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.name %></td>
        <td><%= number_to_currency(plan.price) %></td>
        <td><%= plan.description %></td>
        <td>
          <%= link_to 'Subscribe', subscriptions_path(plan_id: plan.id), method: :post, class: 'btn btn-link' %>
        </td>
        <td>
          <%= link_to 'Edit', [:edit, plan], class: 'btn btn-link' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Subscriptions', subscriptions_path, class: 'btn btn-primary' %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @plan.price %>
</p>

<p>
  <strong>Paypal description:</strong>
  <%= @plan.paypal_description %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plan.description %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>

app/views/subscriptions/index.html.erb
<h1>Subscriptions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Paid until</th>
      <th>Plan</th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td>
          <%= l(subscription.paid_until, format: :long) if subscription.paid? %>
        </td>
        <td><%= subscription.plan %></td>
        <td><%= link_to 'View', subscription %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%=link_to 'Plans', root_path, class: 'btn btn-primary' %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paypal payer ID:</strong>
  <%= subscription.paypal_payer_id %>
</p>

<p>
  <strong>Paypal profile ID:</strong>
  <%= subscription.paypal_profile_id %>
</p>

<% if subscription.paid? %>
    <p>
      <strong>Paid until:</strong>
      <%= l subscription.paid_until, format: :long %>
    </p>
<% end %>

<p>
  <strong>Plan:</strong>
  <%= subscription.plan %>
</p>

<% if subscription.trial? %>
    <div class="alert alert-info">
      Trial ending on <%=subscription.paid_until + 30.days%>
    </div>
<% end %>
<% if subscription.canceled? %>
    <div class="alert alert-warning">
      This subscription has been canceled
    </div>
<% end %>

<% if subscription.paid? || subscription.trial? %>
    <%= link_to 'Cancel',
                subscription_path(subscription),
                method: :delete,
                data: { confirm: 'Are you sure that you want cancel your subscription?' } %> |
<% end %>


<%= link_to 'Back', subscriptions_path, class: 'btn btn-secondary' %>